server:
  port: 8081

spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mybatis/**/*.xml
  type-aliases-package: com.ebiz.zhanye.db.generated.model
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

logging:
  config: classpath:logback/logback.xml
  level:
    com.ebiz.zhanye.db.dao: debug

dozer:
  mapping-files: classpath:dozer/dozer-mapping.xml

# pageHelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


